import time
print('hello and welcome to Alvantia')
print("Let's begin what is your name?")
name = input("Name: ")
print("your name is", name)
print("...... One day", name, "is walking through a forest when all of a sudden")
print("A goblin leaps out of the bush!")
print("would you like to defend or attack?")
attack1 = input("Attack or defend?: ")
print("You", attack1, "the Goblin")
time.sleep(5.5)
