#This is the first time boot
import time
print("Hello and welcome to Trapdoor V1.0")
print ("Let's begin what do you want your username to be?")
username = input("Enter your desired username: ")
print("Thats a nice username", username)
print ("Now how old are you?")
age = input('Enter your age: ')
print ("Ok so you're", age)
password = input("What would you like your password to be?: ")
print("Ok lets setup your wifi")
wifi = input("Whats your wifi name?: ")
wifipass = input("Ok and whats the password?: ")
print("Attempting to join", wifi)
time.sleep(2.2)
print("Joined", wifi,"!")
while 1:
	user = input("So all this information correct?: ")
	if user=="No" or user=="no" or user=="n" or user=="N":
		print("Okay then quit and try again") 
	elif user=="Yes" or user=="yes" or user=="y" or user=="Y": break	
usernameFile = open("username.txt","w")
usernameFile.write(username)
usernameFile.close()
passwordFile = open("password.txt","w")
passwordFile.write(password)
passwordFile.close()
usernameFile = open("check.txt","w")
usernameFile.write("1")
usernameFile.close()
print("So your username is", username)
print("And your age is", age)
print("The wifi you connected to is", wifi)
print("Your password will be", password)
time.sleep(7.7)